# Generated by Django 4.2.23 on 2025-09-13 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SmartWasteApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logintable',
            old_name='StudentName',
            new_name='Username',
        ),
    ]
