# Generated by Django 4.2.23 on 2025-09-27 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SmartWasteApp', '0002_rename_studentname_logintable_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studenttable',
            old_name='userid',
            new_name='LOGIN',
        ),
        migrations.RemoveField(
            model_name='complainttable',
            name='StudentId',
        ),
        migrations.RemoveField(
            model_name='rewardtable',
            name='StudentId',
        ),
        migrations.RemoveField(
            model_name='studenttable',
            name='password',
        ),
        migrations.RemoveField(
            model_name='studenttable',
            name='username',
        ),
        migrations.AddField(
            model_name='bintable',
            name='Date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='complainttable',
            name='STUDENT',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SmartWasteApp.studenttable'),
        ),
        migrations.AddField(
            model_name='rewardtable',
            name='Date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='rewardtable',
            name='STUDENT',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SmartWasteApp.studenttable'),
        ),
        migrations.AddField(
            model_name='studenttable',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studenttable',
            name='age',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='studenttable',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bintable',
            name='BinStatus',
            field=models.CharField(blank=True, default='pending', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bintable',
            name='CollectionStatus',
            field=models.CharField(blank=True, default='pending', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='complainttable',
            name='Date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='studenttable',
            name='mobilenumber',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ContractorTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('mobilenumber', models.BigIntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=250, null=True)),
                ('LOGIN', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SmartWasteApp.logintable')),
            ],
        ),
    ]
