# Generated by Django 4.2.23 on 2025-09-27 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartWasteApp', '0003_rename_userid_studenttable_login_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractortable',
            name='dob',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='contractortable',
            name='email',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='contractortable',
            name='qualification',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
