# Generated by Django 4.2.23 on 2025-11-10 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SmartWasteApp', '0004_contractortable_dob_contractortable_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bintable',
            name='CONTRACTORID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SmartWasteApp.contractortable'),
        ),
    ]
