# Generated by Django 4.2.23 on 2025-11-25 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartWasteApp', '0005_bintable_contractorid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bintable',
            name='CONTRACTORID',
        ),
        migrations.AddField(
            model_name='studenttable',
            name='email',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
