# Generated by Django 4.2.23 on 2025-12-17 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartWasteApp', '0006_remove_bintable_contractorid_studenttable_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductName', models.CharField(blank=True, max_length=50, null=True)),
                ('Prize', models.CharField(blank=True, max_length=50, null=True)),
                ('Image', models.FileField(blank=True, null=True, upload_to='Images')),
                ('Description', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
