# Generated by Django 4.2.23 on 2025-12-17 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SmartWasteApp', '0007_producttable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producttable',
            old_name='Prize',
            new_name='Point',
        ),
    ]
