# Generated by Django 4.2.23 on 2025-12-29 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartWasteApp', '0008_rename_prize_producttable_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='studenttable',
            name='Qr',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
