# Generated by Django 4.2.23 on 2025-12-29 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartWasteApp', '0009_studenttable_qr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studenttable',
            name='Qr',
            field=models.ImageField(blank=True, null=True, upload_to='qr/'),
        ),
    ]
